<a href="https://colab.research.google.com/github/jamessj0412/fmllab/blob/main/fmlnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
print(type(a)),a.shape,a
a[0]=5
print(a)

<class 'numpy.ndarray'>
[5 2 3]


In [ ]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
b[0]

array([1, 2, 3])

In [ ]:
print(b.shape)
print(b[0,0], b[0,1],b[0,2])

(2, 3)
1 2 3


In [ ]:
a=np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [ ]:
b=np.ones((1,2))
print(b)

[[1. 1.]]


In [ ]:
c=np.full((2,2),7)
print(c)

[[7 7]
 [7 7]]


In [ ]:
d=np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [ ]:
e=np.random.random((2,2))
print(e)

[[0.36258368 0.5277496 ]
 [0.0584392  0.35744486]]


Array Indexing

In [ ]:
a=np.array([[1,2,3,4]])
print(a)

[[1 2 3 4]]


In [ ]:
b=a[:2,1:3]
print(b)

[[2 3]]


In [ ]:
print(a[0,1])
b[0,0]=77
print(a[0,1])

2
77


In [ ]:
print(a)
print(b)

[[ 1 77  3  4]]
[[77  3]]


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
row_r1=a[1,:]
row_r2=a[1:2, :]
row_r3=a[[1],:]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r2, row_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
col_r1=a[:,1]
col_r2=a[:,1:2]
print(col_r1,col_r1.shape)
print()
print(col_r2,col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


In [ ]:
a=np.array([[1,2],[3,4],[5,6]])
print(a.shape)

(3, 2)


In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
b = np.array([0, 2, 0, 1])
print(b)

[0 2 0 1]


In [ ]:
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


Datatypes

In [ ]:
x = np.array([1, 2])
y = np.array([1.0, 2.0])
z = np.array([1, 2], dtype=np.int64)

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


Array math

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [ ]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [ ]:
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [ ]:
print(x / y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])
print(v.shape, w.shape)
print(v.dot(w))
print(np.dot(v, w))

print(x.dot(y))

(2,) (2,)
219
219
[[19 22]
 [43 50]]


In [ ]:
z = np.eye(2)
print(x.dot(z))

[[1. 2.]
 [3. 4.]]


In [ ]:
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

[29 67]
[29 67]
[29 67]


In [ ]:
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [ ]:
x = np.array([[1,2],[3,4]])
print(np.sum(x))

10


In [ ]:
print(x)
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

[[1 2]
 [3 4]]
[4 6]
[3 7]


In [ ]:
print(x)
print("transpose\n", x.T)

[[1 2]
 [3 4]]
transpose
 [[1 3]
 [2 4]]


In [ ]:
v = np.array([[1,2,3]])
print(v.shape)
print(v )
print("transpose\n", v.T)

(1, 3)
[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


Broadcasting

In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)
for i in range(4):
    y[i, :] = x[i, :] + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
vv = np.tile(v, (4, 1))
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [ ]:
y = x + vv
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
v = np.array([1,2,3])
w = np.array([4,5])
print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [ ]:
x = np.array([[1,2,3], [4,5,6]])
print(x + v)

[[2 4 6]
 [5 7 9]]
